### ISSUE TITLE
putty app is not working as expected. 

### ISSUE THREAD

**Issue by darkhacknet** [Athena-OS/athena-iso#10]
Hey bro =D 

This distro is amazing, thanks. 

I have an issue when trying to connect to any ip using putty, simply nothing happens. 
Would you be so kind to take a look ? 

Thanks in advance.

**Comment by D3vil0per** [comment]
Hello! Can you detail me all the steps u did?

**Comment by darkhacknet** [comment]
> Hello! Can you detail me all the steps u did?

Please Close this,  I've fixed it.
Thanks.
