### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Sumangal44** [Athena-OS/athena-iso#100]
![IMG_20240102_024122_143@1689740968.jpg](https://github.com/Athena-OS/athena-iso/assets/123644743/2f2fe383-1ed8-4369-880b-07956959c62c)

What the issue

**Comment by D3vil0p3r** [comment]
I'm thinking that issue should be related to the old ISO. That error does not belong to new ISO.

**Comment by Sumangal44** [comment]
You are right.
