### ISSUE TITLE
[BUG]: update fail, levon signature

### ISSUE THREAD

**Issue by Mohadib2** [Athena-OS/athena-iso#103]
### Athena OS version

Athena os

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.1.70-lts

### Repro steps

When updating getting error levon signature.
Latest iso just downloaded it
Fresh installation.
Even in the installation process i saw these error when installer tried to install packages

### Expected behavior

To update

### Actual behavior

Error

**Comment by D3vil0p3r** [comment]
Download [this file](https://github.com/BlackArch/blackarch-site/blob/master/strap.sh) and
```sh
chmod + x strap.sh
sudo ./strap.sh
sudo pacman -Syy
```

**Comment by D3vil0p3r** [comment]
I uploaded a new ISO where I removed BA. Download it and try.

**Comment by D3vil0p3r** [comment]
Both. Use the link in the athenaos.org download link.
