### ISSUE TITLE
[BUG]: Can't update system

### ISSUE THREAD

**Issue by MrDiFazio** [Athena-OS/athena-iso#105]
### Athena OS version

Anthena OS Rolling

### Which environment or technology are you using?

- [ ] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.5.3-zen1-1-zen

### Repro steps

![Снимок экрана от 2024-01-16 14-54-14](https://github.com/Athena-OS/athena-iso/assets/156777332/3d522670-4afc-4603-a7f9-6074e34097e8)

### Expected behavior
Haven't used the system in a while and decided to run it and update it, but it gives an error when updating.

### Actual behavior

sudo pacman -Syu

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-17 18-50-29](https://github.com/Athena-OS/athena-iso/assets/156777332/d5c5fcb8-ee73-4287-aaae-d99aee8c5eb5)
Now i have this eror

**Comment by D3vil0p3r** [comment]
Download [this file](https://github.com/BlackArch/blackarch-site/blob/master/strap.sh) and run it. Then `sudo pacman -Syy`.

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-17 20-37-23](https://github.com/Athena-OS/athena-iso/assets/156777332/b365c635-65a4-4a95-a59c-91d8532595e8)

**Comment by D3vil0p3r** [comment]
Run strap.sh by sudo and give to it executable permission.

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-17 22-13-56](https://github.com/Athena-OS/athena-iso/assets/156777332/60003f3a-7717-44d0-a618-564b239d7212)
Done. But its not working.

**Comment by D3vil0p3r** [comment]
dont care about those first messages. What are the last messages?

**Comment by MrDiFazio** [comment]
> dont care about those first messages. What are the last messages?

![Снимок экрана от 2024-01-17 22-32-59](https://github.com/Athena-OS/athena-iso/assets/156777332/cdd6d9f0-1855-4eb1-a395-95d9403a6f35)
The last mesage: Incorrect or corrupted database

**Comment by MrDiFazio** [comment]
Found this article, tried it but no result.
`You can also import the key into your pacman keyring yourself. This is necessary when the official keyserver does not provide the desired key (yet). To do so, follow the next steps.`
https://aronschueler.de/blog/2022/01/30/arch-signature-is-unknown-trust/

**Comment by D3vil0p3r** [comment]
BlackArch resources currently are producing several issues. I would suggest you to wait we migrate Athena from Arch to Nix.

**Comment by MrDiFazio** [comment]
> BlackArch resources currently are producing several issues. I would suggest you to wait we migrate Athena from Arch to Nix. Or just remove BlackArch mirrors and server references from `pacman.conf`.

I remove it, but it didn't help. The same error as above. So I'll wait for a solution.

**Comment by MrDiFazio** [comment]
I have made this https://blackarch.org/faq.html
Blackarch is working, but other no
![Uploading Снимок экрана от 2024-01-18 22-30-25.png…]()

**Comment by MrDiFazio** [comment]
> Try to run `init-keys` command.
![Снимок экрана от 2024-01-18 22-43-45](https://github.com/Athena-OS/athena-iso/assets/156777332/a9b102be-1cf4-4c68-b202-d730b2295781)

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-18 23-29-07](https://github.com/Athena-OS/athena-iso/assets/156777332/d123fb33-3a50-4b8c-b45a-116cd0166196)
It's done. And it looks like it's working.

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-18 23-29-07](https://github.com/Athena-OS/athena-iso/assets/156777332/c187a235-5f6c-4ed8-8979-e05d338e7ab9)
But there are questions. Which one to choose?

**Comment by D3vil0p3r** [comment]
Try the 1st one.

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-18 23-46-35](https://github.com/Athena-OS/athena-iso/assets/156777332/2ac6d7bf-6f16-4c4e-9c7f-2acf6852b8e5)
At the end I get this error

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-19 00-10-04](https://github.com/Athena-OS/athena-iso/assets/156777332/b29d7551-48ac-4a02-9111-3374a2a04a55)
It's worked! Thanks for help!

**Comment by MrDiFazio** [comment]
![Снимок экрана от 2024-01-19 00-44-32](https://github.com/Athena-OS/athena-iso/assets/156777332/767f1cc4-59c3-472c-a85f-9d6cc52423f6)
Trying to update the system, these errors appear.

**Comment by D3vil0p3r** [comment]
It is the TokyoNight theme that is bugged. U can try to change it or manually reapplying it. I already informed the theme dev

**Comment by MrDiFazio** [comment]
```
`conflicting files:
- tokyonight-gtk-theme-git: /usr/share/themes/Tokyonight-Dark-B/cinnamon/assets/add-workspace-active.svg уже exists on the file system (owner— athena-blue-eyes-theme
```)
`
