### ISSUE TITLE
[BUG]: 离线安装成功 在线安装无网络，安装成功后运行pacman -Sy 失败

### ISSUE THREAD

**Issue by su22cmd** [Athena-OS/athena-iso#106]
### Athena OS version

Athena OSv23.06.23

### Which environment or technology are you using?

- [ ] Baremetal
- [ ] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.3.9-zen1-1-zen

### Repro steps

![image](https://github.com/Athena-OS/athena-iso/assets/71595313/bca0269b-94fe-47ee-a257-e1a93614003c)

pacman -Sy
![image](https://github.com/Athena-OS/athena-iso/assets/71595313/e22bea13-29c8-44bc-99c6-0119d966bae6)

### Expected behavior

![image](https://github.com/Athena-OS/athena-iso/assets/71595313/72f08b69-0f1c-4687-b8f6-89558e428919)

### Actual behavior

![image](https://github.com/Athena-OS/athena-iso/assets/71595313/682d63eb-42e9-4809-9b21-d5b0d9c13e2d)

└──╼[👾]/home/toor/Desktop $ pacman -Sy
:: Synchronizing package databases...
 athena-repository.db failed to download
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur              2.6 MiB  99.5 KiB/s 00:27 [---------------------------] 100%
 blackarch                   4.0 MiB  44.7 KiB/s 01:32 [-----------------------------] 100%
error: failed retrieving file 'athena-repository.db' from athena-os.github.io : The requested URL returned error: 404
error: failed retrieving file 'athena-repository.db' from mirror.pardesicat.xyz : The requested URL returned error: 404
error: failed retrieving file 'chaotic-aur.db' from cdn-mirror.chaotic.cx : SSL connection timeout
error: failed retrieving file 'chaotic-aur.db' from geo-mirror.chaotic.cx : Failed to connect to cf-builds.garudalinux.org port 443 after 10000 ms: Timeout was reached
error: failed retrieving file 'chaotic-aur.db' from au-mirror.chaotic.cx : The requested URL returned error: 404
error: failed retrieving file 'chaotic-aur.db' from au-2-mirror.chaotic.cx : The requested URL returned error: 404
error: failed to synchronize all databases (unexpected error)

**Comment by D3vil0p3r** [comment]
* Solution: edit `/etc/pacman.conf` and replace `[athena-repository]` by `[athena]`. Then replace the content of `/etc/pacman.d/athena-mirrorlist` by:
```
# Global
Server = https://athena-os.github.io/$repo-repository/$arch

# Lithuania
Server = https://hub.athenaos.org/$repo/$arch
```

**Comment by su22cmd** [comment]
and this error, i use proxy but still have timeout

![image](https://github.com/Athena-OS/athena-iso/assets/71595313/ad45f087-e033-4fe0-974f-e391af85c630)

:: Synchronizing package databases...
 athena is up to date
 core                  129.0 KiB  84.8 KiB/s 00:02 [----------------------] 100%
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
 blackarch is up to date
error: failed retrieving file 'chaotic-aur.db' from cdn-mirror.chaotic.cx : Failed to connect to cf-builds.garudalinux.org port 443 after 10000 ms: Timeout was reached
error: failed retrieving file 'chaotic-aur.db' from geo-mirror.chaotic.cx : Failed to connect to cf-builds.garudalinux.org port 443 after 10002 ms: Timeout was reached
error: failed retrieving file 'chaotic-aur.db' from au-mirror.chaotic.cx : The requested URL returned error: 404
error: failed retrieving file 'chaotic-aur.db' from au-2-mirror.chaotic.cx : The requested URL returned error: 404

**Comment by su22cmd** [comment]
ok, thanks
