### ISSUE TITLE
Theme is not installed after installing AthenaOS.

### ISSUE THREAD

**Issue by mkdirlove** [Athena-OS/athena-iso#11]
Theme is not installed by default after installing the OS.

I choosed the blue eye samurai theme on installation but after rebooting, the theme is not installed.

How do i install any theme?

Is there a script that can install themes?

**Comment by D3vil0per** [comment]
Hey. The theme should install automatically at the installation phase but only if you are connected to Internet. Were you connected to Internet after installation?

**Comment by mkdirlove** [comment]
I have no internet connection upon installing Athena OS.
I'll try installing it again but with internet connection.


Thanks :)

**Comment by D3vil0per** [comment]
> I have no internet connection upon installing Athena OS. I'll try installing it again but with internet connection.
> 
> Thanks :)

Hey @mkdirlove , anyway on Athena Repository, if you install `sudo pacman -Syy athena-theme-tweak` you can use athena-theme-tweak command for installing and changing Athena themes.
For example `athena-theme-tweak -l` will list the current available themes, while `athena-theme-tweak -t BlueEyesSamurai` will set the theme of the Blue Eyes anime samurai. Try it and let me know :)
