### ISSUE TITLE
[ENHANCEMENT] Docker Container

### ISSUE THREAD

**Issue by 4l13nC0d3rs** [Athena-OS/athena-iso#12]
hey can create a docker, i want to run it over rdp

**Comment by D3vil0per** [comment]
Hey mate. I think I will consider the usage of docker, because it could open new interesting scenarios

**Comment by D3vil0p3r** [comment]
Hey @4l13nC0d3rs Athena OS docker container for RDP is out, currently for testing purpose. Give a look to https://github.com/Athena-OS/athena-rdp-docker
