### ISSUE TITLE
can not log in

### ISSUE THREAD

**Issue by Biaogo** [Athena-OS/athena-iso#16]
It seems that every time you log in, you need to connect to the Internet to download something. For countries with network speed restrictions, you can't log in.
![图片](https://user-images.githubusercontent.com/56547184/188261153-d039f83b-69ca-4376-857d-748945843b53.png)
I tried turning off networking at the login screen, which allowed me to log in to the desktop

**Comment by D3vil0per** [comment]
> It seems that every time you log in, you need to connect to the Internet to download something. For countries with network speed restrictions, you can't log in. ![图片](https://user-images.githubusercontent.com/56547184/188261153-d039f83b-69ca-4376-857d-748945843b53.png) I tried turning off networking at the login screen, which allowed me to log in to the desktop

Strange behavior. Can you retrieve error GDM and GNOME logs and paste here? So I can investigate. Thanks

**Comment by Biaogo** [comment]
I installed the latest version of athena-os on vbox, I gave 4g of memory and 4 processors, but it often gets stuck and some places can't display properly. And I also need the network for the second login
![图片](https://user-images.githubusercontent.com/56547184/188299396-0179dbec-4e38-4e8e-a51d-e8bfbe2791ab.png)

**Comment by D3vil0per** [comment]
> I installed the latest version of athena-os on vbox, I gave 4g of memory and 4 processors, but it often gets stuck and some places can't display properly. And I also need the network for the second login ![图片](https://user-images.githubusercontent.com/56547184/188299396-0179dbec-4e38-4e8e-a51d-e8bfbe2791ab.png)

Which specific languages are you setting on "Locale" section of the Installer? (Time zone, system language, and so on)

**Comment by Biaogo** [comment]
> > I installed the latest version of athena-os on vbox, I gave 4g of memory and 4 processors, but it often gets stuck and some places can't display properly. And I also need the network for the second login ![图片](https://user-images.githubusercontent.com/56547184/188299396-0179dbec-4e38-4e8e-a51d-e8bfbe2791ab.png)
> 
> Which specific languages are you setting on "Locale" section of the Installer? (Time zone, system language, and so on)

No, I tried to set the proxy in live, and it looks like this

**Comment by D3vil0per** [comment]
> > > I installed the latest version of athena-os on vbox, I gave 4g of memory and 4 processors, but it often gets stuck and some places can't display properly. And I also need the network for the second login ![图片](https://user-images.githubusercontent.com/56547184/188299396-0179dbec-4e38-4e8e-a51d-e8bfbe2791ab.png)
> > 
> > 
> > Which specific languages are you setting on "Locale" section of the Installer? (Time zone, system language, and so on)
> 
> No, I tried to set the proxy in live, and it looks like this

Which proxy did you set?

**Comment by Biaogo** [comment]
> 

As soon as the window is opened, the screen will be blurred. I don't know if it has successfully set the proxy. I don't think this is a problem with the proxy interface, and the system will freeze after a while.

> > > > 我安装了最新版本的athena-os在竖直盒子，我给4g的存储器和4个处理器，但它经常得到坚持和一些地方不可能显示正常。 并且我还需要一网络的第二登录  ![图片](https://user-images.githubusercontent.com/56547184/188299396-0179dbec-4e38-4e8e-a51d-e8bfbe2791ab.png)
> > > 
> > > 
> > > 其特定语言都是你设置在"区域"部分的安装? (次区域、系统语言，等等)
> > 
> > 
> > 没有，我试图设置的代理活，并且它看起来像这样
> 
> 其代理你有没有设置？

As soon as the window is opened, the screen will be blurred. I don't know if it has successfully set the proxy. I don't think this is a problem with the proxy interface, and the system will freeze after a while.

**Comment by D3vil0per** [comment]
@Biaogo that blurred screen could be caused by 3D Acceleration settings enabled on VirtualBox settings of your VM. If you enabled it, try to disable it and check if it is displayed correctly after a reboot.

Meanwhile I'm changing some login script for avoiding the long wait on the Login screen when the user is not connected to Internet, and I'm implementing also China-Japan-Korean fonts because currently not installed.

**Comment by Biaogo** [comment]
> @Biaogo that blurred screen could be caused by 3D Acceleration settings enabled on VirtualBox settings of your VM. If you enabled it, try to disable it and check if it is displayed correctly after a reboot.
> 
> Meanwhile I'm changing some login script for avoiding the long wait on the Login screen when the user is not connected to Internet, and I'm implementing also China-Japan-Korean fonts because currently not installed.

Thank you, I'll try turning it off, it's missing some fonts, I'm currently using `wqy-microhei`

**Comment by D3vil0p3r** [comment]
Solved
