### ISSUE TITLE
[ENHANCEMENT] xfce edition

### ISSUE THREAD

**Issue by cocoonkid** [Athena-OS/athena-iso#17]
**Is your feature request related to a problem? Please describe.**

Gnome is slow. XFCE is fast.

**Describe the solution you'd like**

an XFCE Edition

Thanks for consideration

**Comment by D3vil0p3r** [comment]
Hey @cocoonkid in the future Athena will provide also other Desktop Environments (as XFCE). The project will provide them when main elements of Athena, that currently work only on GNOME, will work also for other Desktop Environments.

**Comment by cocoonkid** [comment]
Thanks a bunch for taking the time to reply.

Highly appreciated.

May I ask which are these main elements specifically?

**Comment by D3vil0p3r** [comment]
> Thanks a bunch for taking the time to reply.
> 
> Highly appreciated.
> 
> May I ask which are these main elements specifically?

@cocoonkid they are PenTOXIC and PWNage menus, the app dock menu.

**Comment by p134c0d3** [comment]
@cocoonkid new iso was released utilizing XFCE env in rolling releases. If you want to give it a try it's at https://sourceforge.net/projects/athena-iso/files/rolling/

**Comment by D3vil0p3r** [comment]
> @cocoonkid new iso was released utilizing XFCE env in rolling releases. If you want to give it a try it's at https://sourceforge.net/projects/athena-iso/files/rolling/

Thank you very much @p134c0d3 for the reminder. I close the issue as solved.
