### ISSUE TITLE
Install error dependency 

### ISSUE THREAD

**Issue by taycom** [Athena-OS/athena-iso#18]
Problems with dependency on mutter on the installation process

**Describe the bug**
warning: removing 'mutter' from target list because it conflicts with 'mutter-performance'
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'libmutter-11.so=0-64' required by gnome-shell
2022-11-02 - 08:31:24 [2]: WARNING: [PYTHON JOB]: "Command 'pacman' returned non-zero exit status 1." 

**To Reproduce**
1. Install 
2. Select Linux Kernel - by default
3. Select xf86-video-vesa
4. Select VirtualBox option
5. Gnome Display Manager
6. Any specific change in the rest of windows

**Log from Installer**
https://termbin.com/0yag

**Desktop (please complete the following information):**
 - OS: VirtualBox 6.1

**Additional context**

**Comment by D3vil0p3r** [comment]
> Problems with dependency on mutter on the installation process
> 
> **Describe the bug** warning: removing 'mutter' from target list because it conflicts with 'mutter-performance' error: failed to prepare transaction (could not satisfy dependencies) :: unable to satisfy dependency 'libmutter-11.so=0-64' required by gnome-shell 2022-11-02 - 08:31:24 [2]: WARNING: [PYTHON JOB]: "Command 'pacman' returned non-zero exit status 1."
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install
> 2. Select Linux Kernel - by default
> 3. Select xf86-video-vesa
> 4. Select VirtualBox option
> 5. Gnome Display Manager
> 6. Any specific change in the rest of windows
> 
> **Log from Installer** https://termbin.com/0yag
> 
> **Desktop (please complete the following information):**
> 
> * OS: VirtualBox 6.1
> 
> **Additional context** Add any other context about the problem here.

Hello @taycom This issue is related by the newest library updates affecting GNOME. The problem is generally solved when I will release the new version of Athena. The most easily solution you can adopt is to create the ISO in your own. If you are interested in this temporary solution, tell me and I will write all the steps you need (pretty easy).

Otherwise we need to wait for the next release.

**Comment by Bubbybabe0630** [comment]
Hello, I am having this same exact issue. During the install, it tries to run update, and the dependencies conflict with one another for Mutter. So I am interested in the steps on how to fix this issue. Because I have even tried older versions and the install keeps failing because of this bug.

**Comment by D3vil0p3r** [comment]
> 

Yes @Bubbybabe0630. Probably tomorrow or on Saturday, I will release the new version of Athena that solves this issue and add a lot of changes (mostly on the kernel). If you can wait this time, I'll appreciate.

**Comment by blackguy123456** [comment]
> Yes @Bubbybabe0630. Probably tomorrow or on Saturday, I will release the new version of Athena that solves this issue and add a lot of changes (mostly on the kernel). If you can wait this time, I'll appreciate.

Hello Mr D3vilop3r , 
I am wondering what the issue is with the speed of Athena. What I mean is, when I update/install packages the download speeds are extremely slow (I’ve used blackarch as daily driver for over 1 year so I am familiar with mirrors, I updated my mirrors with reflector, connected to Ethernet, etc.) but for some reason everything moves extremely slow. Any solution you could think of? Or am I the only one with this and maybe I need to rtfm 😂

**Comment by D3vil0p3r** [comment]
> > Yes @Bubbybabe0630. Probably tomorrow or on Saturday, I will release the new version of Athena that solves this issue and add a lot of changes (mostly on the kernel). If you can wait this time, I'll appreciate.
> 
> Hello Mr D3vilop3r , I am wondering what the issue is with the speed of Athena. What I mean is, when I update/install packages the download speeds are extremely slow (I’ve used blackarch as daily driver for over 1 year so I am familiar with mirrors, I updated my mirrors with reflector, connected to Ethernet, etc.) but for some reason everything moves extremely slow. Any solution you could think of? Or am I the only one with this and maybe I need to rtfm 😂

Uhm, reflector should not work with BlackArch... it should work only by ArchLinux repositories. Anyway, if you reach me on Discord, I can use you as a tester with the new ISO for checking if it works. Do you have a Discord account? If so, reach me here:  https://discord.gg/GuDyREsNkj

**Comment by blackguy123456** [comment]
Correct, I meant to say I use it for the arch mirrors, not blackarch mirrorlist. I ran black arch iso as my OS. I will head over to discord!  I’m liking how this project is turning out and would love to aid in any way possible!

**Comment by D3vil0p3r** [comment]
> Correct, I meant to say I use it for the arch mirrors, not blackarch mirrorlist. I ran black arch iso as my OS. I will head over to discord! I’m liking how this project is turning out and would love to aid in any way possible!

I appreciate it a lot ^^

**Comment by D3vil0p3r** [comment]
@blackguy123456 @taycom The new release is out. Download it and tell me please if it can be installed, so I can close the ticket. Thanks

**Comment by D3vil0p3r** [comment]
Fixed
