### ISSUE TITLE
You can connect to the network, but you can't update the mirror

### ISSUE THREAD

**Issue by no3586** [Athena-OS/athena-iso#20]
![image](https://user-images.githubusercontent.com/95933876/205447218-0186bc95-7c4e-40c4-b05d-e830505f447e.png)

**Comment by no3586** [comment]
And the yellow font shows that there is no network

**Comment by D3vil0p3r** [comment]
> And the yellow font shows that there is no network

@no3586 hey mate. If you are from China, I suggest you to use a VPN because we noted that the Great Firewall in China blocks a lot of connections. By using VPN, it should solve the issue.

**Comment by D3vil0p3r** [comment]
Fixed in the latest release.
