### ISSUE TITLE
The installer keeps getting stuck at 69 percent

### ISSUE THREAD

**Issue by no3586** [Athena-OS/athena-iso#21]
![image](https://user-images.githubusercontent.com/95933876/205447346-8e231878-73b0-4bd8-ba60-b1adfda16af5.png)

**Comment by D3vil0p3r** [comment]
> ![image](https://user-images.githubusercontent.com/95933876/205447346-8e231878-73b0-4bd8-ba60-b1adfda16af5.png)

At 69% is not stucking, it is downloading things from Internet. The performance depends on the speed of your connection. Leave it working and then it will move from 69% to the end of installation.
