### ISSUE TITLE
Man command error [BUG]

### ISSUE THREAD

**Issue by 0xViKi** [Athena-OS/athena-iso#22]
**Describe the bug**
man command throws error when tried to view manual page for any command.

**To Reproduce**
In terminal:
$ man man

**Screenshots**
---
![ss](https://user-images.githubusercontent.com/73846668/205852941-c4103e85-3b82-4a70-ad00-a91610986766.png)

**Solution**
---
****edit ~/.bashrc config****
```.sh 
export PAGER=less
or
export PAGER=more
```

**Comment by D3vil0p3r** [comment]
Fixed in the latest release.
