### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wagnnerX** [Athena-OS/athena-iso#26]
Hello, thanks, I found your distro on a page and I'm using it but I can't install it because of the package error when I finish installing grub through livecd .. and I tried to download the current one but it's not available

**Comment by wagnnerX** [comment]
I would like to have the honor of participating in your project my friend sorry if I write badly I am Brazilian linux user window not desktop thank you

**Comment by wagnnerX** [comment]
aguardo respostas obrigado

**Comment by D3vil0p3r** [comment]
Hello @wagnnerX The new version of Athena OS has been released. It should fix your issue. Try it.

**Comment by wagnnerX** [comment]
yes it solved for me Athena OS "Parthenos" I did clean installation and
everything working gnome with tiling windows too good

Em seg., 23 de jan. de 2023 às 16:13, D3vil0p3r ***@***.***>
escreveu:
