### ISSUE TITLE
Adding torrent to download link

### ISSUE THREAD

**Issue by pinklettuce** [Athena-OS/athena-iso#29]
Due to the slow speeds you should implement a download option for a torrent in the future

**Comment by expandpi** [comment]
Athena now supports torrent downloading with the help [FossTorrents](https://fosstorrents.com/distributions/athena-os/)

Thanks for the suggestion.

**Comment by phanirithvij** [comment]
@expandpi the fosstorrents iso is outdated, any plans to keep it uptodate?

**Comment by expandpi** [comment]
Hey! @phanirithvij 
Yeah we know. We need to come with a new implementation for torrent. We are testing fedora and athena flow is that iso will build on daily basis and upload on the drive. So its not possible to upload on fosstorrent daily until they use some automation  or create a user interface which allows us to do that.
