### ISSUE TITLE
In athena os wifi options are not visible. On lenevo ideapad 520

### ISSUE THREAD

**Issue by adsulshyam0000** [Athena-OS/athena-iso#3]
Not able to connect wifi in athena os.

**Comment by D3vil0per** [comment]
> Not able to connect wifi in athena os.

Thanks for reporting this issue. Are you using Athena on VirtualBox, VMware or native or other? Which wifi ethernet card are u using?

**Comment by adsulshyam0000** [comment]
I am using it as native tried to figure it out still issue exist.

**Comment by adsulshyam0000** [comment]
dmesg | grep firmware
[    0.136795] Spectre V2 : Enabling Restricted Speculation for firmware calls
[   13.890654] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[   14.026355] i915 0000:00:02.0: Direct firmware load for i915/kbl_dmc_ver1_04.bin failed with error -2
[   14.026364] i915 0000:00:02.0: [drm] Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin. Disabling runtime power management.
[   14.026368] i915 0000:00:02.0: [drm] DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[   14.272626] nouveau 0000:01:00.0: acr: firmware unavailable
[   14.272629] nouveau 0000:01:00.0: pmu: firmware unavailable
[   14.272721] nouveau 0000:01:00.0: gr: firmware unavailable
[   16.217005] ath10k_pci 0000:03:00.0: Failed to find firmware-N.bin (N between 2 and 6) from ath10k/QCA6174/hw3.0: -2
[   16.217011] ath10k_pci 0000:03:00.0: could not fetch firmware files (-2)
[   28.502218] r8169 0000:02:00.0: Direct firmware load for rtl_nic/rtl8168g-3.fw failed with error -2
[   28.502234] r8169 0000:02:00.0: Unable to load firmware rtl_nic/rtl8168g-3.fw (-2)
[10309.486843] bluetooth hci0: Direct firmware load for qca/rampatch_usb_00000302.bin failed with error -2
[10309.490565] r8169 0000:02:00.0: Direct firmware load for rtl_nic/rtl8168g-3.fw failed with error -2
[10309.490571] r8169 0000:02:00.0: Unable to load firmware rtl_nic/rtl8168g-3.fw (-2)

**Comment by D3vil0per** [comment]
> dmesg | grep firmware [ 0.136795] Spectre V2 : Enabling Restricted Speculation for firmware calls [ 13.890654] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2 [ 14.026355] i915 0000:00:02.0: Direct firmware load for i915/kbl_dmc_ver1_04.bin failed with error -2 [ 14.026364] i915 0000:00:02.0: [drm] Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin. Disabling runtime power management. [ 14.026368] i915 0000:00:02.0: [drm] DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915 [ 14.272626] nouveau 0000:01:00.0: acr: firmware unavailable [ 14.272629] nouveau 0000:01:00.0: pmu: firmware unavailable [ 14.272721] nouveau 0000:01:00.0: gr: firmware unavailable [ 16.217005] ath10k_pci 0000:03:00.0: Failed to find firmware-N.bin (N between 2 and 6) from ath10k/QCA6174/hw3.0: -2 [ 16.217011] ath10k_pci 0000:03:00.0: could not fetch firmware files (-2) [ 28.502218] r8169 0000:02:00.0: Direct firmware load for rtl_nic/rtl8168g-3.fw failed with error -2 [ 28.502234] r8169 0000:02:00.0: Unable to load firmware rtl_nic/rtl8168g-3.fw (-2) [10309.486843] bluetooth hci0: Direct firmware load for qca/rampatch_usb_00000302.bin failed with error -2 [10309.490565] r8169 0000:02:00.0: Direct firmware load for rtl_nic/rtl8168g-3.fw failed with error -2 [10309.490571] r8169 0000:02:00.0: Unable to load firmware rtl_nic/rtl8168g-3.fw (-2)

It can be fixed by installing `linux-firmware`. I don't think the Live Env has enough space for it, but I can release quickly an ISO with this fix and also other fixes related to the operativity.

**Comment by adsulshyam0000** [comment]
Fixed issue resolved thanks for your help.

 1. Install linux-firmware package

Please follow the step by step instructions below to install linux-firmware package:
sudo pacman -Sy
sudo pacman -S linux-firmware
2. Uninstall / Remove linux-firmware package

This is a short guide on how to uninstall linux-firmware package:
sudo pacman -Rcns linux-firmware
