### ISSUE TITLE
Desktop env

### ISSUE THREAD

**Issue by Radeonares32** [Athena-OS/athena-iso#30]
would you consider adding a tile manager like bspwm i3, it would be great

**Comment by D3vil0p3r** [comment]
> would you consider adding a tile manager like bspwm i3, it would be great

Hey! Yes, we are working on it. Currently, you can use the Auto Tiling feature for simulating a tile manager working. Just enable this:
![image](https://user-images.githubusercontent.com/83867734/218092312-63596faa-ae96-421d-8c15-ecabcb191237.png)
