### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Ty3TPe9P** [Athena-OS/athena-iso#33]
I decided to install Athena OS instead of another system, burned an ISO to my flash drive and tried to install it to my laptop, but everytime i got this error:
https://termbin.com/s1ev4
Mb i messed up with partition part of installation, can u help me? (srry 4 my bad english) ^^

**Comment by D3vil0p3r** [comment]
> I decided to install Athena OS instead of another system, burned an ISO to my flash drive and tried to install it to my laptop, but everytime i got this error: https://termbin.com/s1ev4 Mb i messed up with partition part of installation, can u help me? (srry 4 my bad english) ^^

Hey mate. I did some changes on packages impacting the installation. I just created the new ISO and I'm testing the installation. If everything will be fine, I will publish the new ISO as minor release.

**Comment by D3vil0p3r** [comment]
@Ty3TPe9P the new ISO is out. Please, use it and let me know if it works.

**Comment by Ty3TPe9P** [comment]
Tested it, worked 4 me, thx👍

пн, 20 февр. 2023 г. в 04:18, D3vil0p3r ***@***.***>:
