### ISSUE TITLE
 Freezing at Started Hostname Service with a flashing screen[BUG]

### ISSUE THREAD

**Issue by Chipsum** [Athena-OS/athena-iso#34]
**Describe the bug**
Freezing at Started Hostname Service with a flashing screen

**To Reproduce**
starting the distro from usb flash drive
I did choose nvidia option, I have GT 710

**Screenshots**
https://photos.app.goo.gl/4Gtia3sabmuAb8fQ7

**Desktop (please complete the following information):**
 - OS: latest one

**Comment by D3vil0p3r** [comment]
Hey @Chipsum could you please give me the details of your computer? CPU, RAM, GPU (Integrated and Dedicated) and so on.

**Comment by Chipsum** [comment]
@D3vil0p3r One moment, I am trying to boot without the nvidia first.
then if it fails I will load another working distro and provide a full inxi.

**Comment by Chipsum** [comment]
Without booting with nvidia option Athena successfully started.

Here is probe:
https://linux-hardware.org/?probe=fd2b985f41

**Comment by D3vil0p3r** [comment]
> Without booting with nvidia option Athena successfully started.
> 
> Here is probe: https://linux-hardware.org/?probe=fd2b985f41

I should remove that NVIDIA option because it is managed at installation time. Let me know if Athena installs correctly.

**Comment by Chipsum** [comment]
I was indeed installing Athena, finished, rebooted, now it's stuck for more than two hours at:
Starting systemd-udevd version 253-1-arch.

**Comment by D3vil0p3r** [comment]
> I was indeed installing Athena, finished, rebooted, now it's stuck for more than two hours at: Starting systemd-udevd version 253-1-arch.

It is an issue, it should enter in some minutes. Press CTRL+ALT+F2 and you should get the tty shell. Login there and run `sudo journalctl -xe | tb ` and send me the generated link. Meanwhile join on Discord so I can follow you better.

**Comment by Chipsum** [comment]
I did boot the live Athena again, run the installer again, and I did almost selected NOTHING especially in drivers section.
After installing, rebooting, successfully loaded into Athena GUI or Gnome or whatever..

I think the problem is clear, no wonders why Linus flipped out nvidia.
The problem then it's not related to Athena or even Arch or even any linux distro, rather than NVIDIA.

I would strongly suggest to make the installer automatic like Mint/Ubuntu/Debian-like for drivers.

Case closed.

**Comment by Chipsum** [comment]
![Screenshot from 2023-02-21 15-36-57](https://user-images.githubusercontent.com/37517008/220375088-284c823e-febe-4592-abb1-7354ef95bf2b.png)

**Comment by D3vil0p3r** [comment]
Closing the issue because solved by your solution:
1. choose the first row in boot options, the one WITHOUT Nvidia in it.
2. When Installing Athena, I did not choose anything, except software like selecting Firefox checkbox, Kitty terminal, but drivers ? Nothing.
3. That's it.
