### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by ColdSteel0204** [Athena-OS/athena-iso#35]
## Question
What is the liveuser pw? I've different selections during install and when I open Bash I'm  labeled as liveuser

**Comment by D3vil0p3r** [comment]
> ## Question
> 
> What is the liveuser pw? I've different selections during install and when I open Bash I'm labeled as liveuser

liveuser password should not be defined. Indeed if you use sudo, it goes without a password.

**Comment by ColdSteel0204** [comment]
Thank  you!
