### ISSUE TITLE
Unable to add/update HTB API Key

### ISSUE THREAD

**Issue by Super-6-1** [Athena-OS/athena-iso#39]
Athena is fully up to date, when i try to add my API key to htb-update is get this error, 

`Error. Maybe your API key is incorrect or expired. Renew your API key and rerun 'htb-update', or insert the new API key in the 'Password' field.
Password: 
Error. Maybe your API key is incorrect or expired. Renew your API key and rerun 'htb-update', or insert the new API key in the 'Password' field. Closing...`

When i run it as sudo with the same command i get this. 

`Error. Maybe your API key is incorrect or expired. Renew your API key and rerun 'htb-update', or insert the new API key in the 'Password' field.
Password: 
secret-tool: Error spawning command line “dbus-launch --autolaunch=69bf687613374d0a91072e71442c708d --binary-syntax --close-stderr”: Child process exited with code 1
Error. Maybe your API key is incorrect or expired. Renew your API key and rerun 'htb-update', or insert the new API key in the 'Password' field. Closing...`

the API key is right, i have regenerated it and still the same issue comes up. Anything that can be done? 

Running it threw VMWare

**Comment by D3vil0p3r** [comment]
Hey @Super-6-1 it could be you are using the wrong token. Can you tell me what are the specific steps when you retrieve your API key from HTB website?

**Comment by Super-6-1** [comment]
Log into hackthebox,com/login
Go to the profile at the top right and click settings under actions
Under API key i copy and paste that. 

I also tested this on my other machine and same issue. Do you have to pay for HTB to get this access?

**Comment by D3vil0p3r** [comment]
> hey @D3vil0p3r yeah, here are the steps i take
> 
> Log into hackthebox,com/login Go to the profile at the top right and click settings under actions Under API key i copy and paste that.
> 
> I also tested this on my other machine and same issue. Do you have to pay for HTB to get this access?

![image](https://user-images.githubusercontent.com/83867734/222229999-cd2cb22d-52a9-4088-8115-e2f962e615ed.png)

Is this what you create?

**Comment by Super-6-1** [comment]
> > hey @D3vil0p3r yeah, here are the steps i take
> > Log into hackthebox,com/login Go to the profile at the top right and click settings under actions Under API key i copy and paste that.
> > I also tested this on my other machine and same issue. Do you have to pay for HTB to get this access?
> 
> ![image](https://user-images.githubusercontent.com/83867734/222229999-cd2cb22d-52a9-4088-8115-e2f962e615ed.png)
> 
> Is this what you create?

No I used something different under settings menu. I'll see if this works.

**Comment by Super-6-1** [comment]
Issue is resolved, incase this happens again, you need to use the new GUI website and not the old school one. This was my issue and i found the right API token. 

thanks for the reply!
