### ISSUE TITLE
[ENHANCEMENT] Hyprland edition

### ISSUE THREAD

**Issue by etherrorcode404** [Athena-OS/athena-iso#40]
[Hyprland](https://github.com/hyprwm/Hyprland) is arguably the future of linux. Its extremely stable and modern a much better replacement for bspwm. Its lightweight and it seems meaningful to make the flagship edition of athena. I can keep going on and on...
So to sum things up it can be both beginner friendly and advanced.

**Comment by etherrorcode404** [comment]
i'm not sure how your implementing user configs, if you give me the idea i could create a PR, it wouldn't take too much effort since the base if already configured. Configuring Hyprland's waybar is the only thing that requires theming and the rest can remain untouched with a minimal hyprland config. Additionally for the wallpaper [hyprpaper](https://github.com/hyprwm/hyprpaper) is a good fit

**Comment by D3vil0p3r** [comment]
Hey @etherrorcode404 I would like to implement all DE and WM but I read not good things about supporting it. Can you list me the advantages and drawbacks of using Hyprland?

**Comment by etherrorcode404** [comment]
> Hey @etherrorcode404 I would like to implement all DE and WM but I read not good things about supporting it. Can you list me the advantages and drawbacks of using Hyprland?

I appreciate your energy, but as much as i want it to be possible its simply a bad idea to say "ALL" DE/WMs since new software keeps on coming with new bugs new features. It all comes down to personal preferences. Supporting everything is nearly impossilbe and at same times useless. Its best to ship with a flagship DE and a flagship WM and if someone want to use something else provide the installation option for that with the optional base customiztions. A great example is endevour OS which provides community editions. As for hyprland you need to try it yourself and judge. As for the things you read, i and most of linux community might disagree. I could link you to things. Infact, ppl who are considered linux elitist have said great things. As, for wayland i hope i dont have to tell why its better. If you feel something as old and unmaintained like bspwm will be a better fit, i really hope you are thinking about it wisely. GOOD LUCK :)

https://arewewaylandyet.com/
https://hyprland.org/
https://youtu.be/wNL6eIoksd8
https://youtu.be/KlDxjrXVW6Q
https://youtu.be/e89w9IFFut0

PS: if you do choose to add hyprland i would love to contribute, else feel free to close this issue

**Comment by jpierce-coder** [comment]
I can't wait for the Hyprland version to come out. If it's a fraction of the quality of the current OS, it'll still be amazing. Sitting on the edge of my seat waiting for that day when it comes out!

**Comment by D3vil0p3r** [comment]
FYI: I'm actively working on implementing Hyprland. In the next period I could open a beta testing about it.

**Comment by D3vil0p3r** [comment]
Hyprland implemented in the latest release.
