### ISSUE TITLE
[BUG] Gray terminal 

### ISSUE THREAD

**Issue by Am1rTl** [Athena-OS/athena-iso#41]
Hello everyone. I have a problem. My terminal becomes gray after I don't interact with it for a while. It works normally, but after I run some long-running program, after some time I see a gray window instead of the terminal. Can you help me fix it?
![image](https://user-images.githubusercontent.com/75519329/222949927-22267937-5318-4965-b201-4cf811e9eb6a.png)

**Comment by D3vil0p3r** [comment]
Hey @Am1rTl  are you in baremetal or VM? Are you using Wayland or Xorg?

Can you open a terminal and run `glxinfo | grep OpenGL` and give me the output?

**Comment by Am1rTl** [comment]
Hi @D3vil0p3r. I use **wayland**
Command result  `glxinfo | grep OpenGL`
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce 940MX/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.89.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 525.89.02
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 525.89.02
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by D3vil0p3r** [comment]
@Am1rTl  try to reset Kitty config file by `mv $HOME/.config/kitty/kitty.conf $HOME/.config/kitty/kitty.conf.bak`. It should reset your Kitty config and check if it happens again (the kitty theme should change).

**Comment by D3vil0p3r** [comment]
No feedback. Closing...
