### ISSUE TITLE
[ENHANCEMENT] increase support

### ISSUE THREAD

**Issue by 2956661656** [Athena-OS/athena-iso#42]
I hope to increase support for China. In China, I can't even pass the first step. Only the network conditions are not satisfied.
**thank you.**

**Comment by Inverstar** [comment]
Me too！
I like this linux system！
But I can't install，may I need VPN for connect network？
I will try it again!
Thank you！

**Comment by 2956661656** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by D3vil0p3r** [comment]
Hello! Yes, I would like to support China users. I must think about a strategy. If you have some suggestions for implementing it, please tell me so I can use it on Athena.

**Comment by Inverstar** [comment]
> Hello! Yes, I would like to support China users. I must think about a strategy. If you have some suggestions for implementing it, please tell me so I can use it on Athena.

Hello, I encountered a problem on the network when installing Athena, we could not directly connect to the foreign network, and the first step of the installation was hindered, so I hope to have an offline installation method or other solutions

**Comment by D3vil0p3r** [comment]
Meanwhile can you use a VPN?

**Comment by Inverstar** [comment]
> Meanwhile can you use a VPN?

I use it on Windows with clash for windows, but in Linux, I install this VPN software fails, I will try again tonight, hope for success！

**Comment by Inverstar** [comment]
Failed, didn't find the VPN are available, and in the case of can't connected to the Internet, there is no Chinese keyboard, everything appears very difficult 😣
Hope to have Chinese pinyin input method and offline installer or offline mode.

**Comment by D3vil0p3r** [comment]
> Failed, didn't find the VPN are available, and in the case of can't connected to the Internet, there is no Chinese keyboard, everything appears very difficult 😣 Hope to have Chinese pinyin input method and offline installer or offline mode.

When I start to go deep on this stuff for chinese users, I could need your help

**Comment by Inverstar** [comment]
OK, I would be happy to help you when you need. And I find a  
way to go， this is a video for propagandaing Athena，in its  comments section 。I will try to install again！

【Athena OS 2023.02.20 概览 | 一个基于Arch linux的发行版-哔哩哔哩】 https://b23.tv/T1RDwYg

**Comment by Inverstar** [comment]
> > Failed, didn't find the VPN are available, and in the case of can't connected to the Internet, there is no Chinese keyboard, everything appears very difficult 😣 Hope to have Chinese pinyin input method and offline installer or offline mode.
> 
> When I start to go deep on this stuff for chinese users, I could need your help

what's root's password？ I want to change URL in welcome file.

**Comment by Inverstar** [comment]
Thank god, solve the network, modify the welcome file, execute the known error command before installation, and finally install successfully！

**Comment by D3vil0p3r** [comment]
Summarizing: on Athena the Internet connection check is done on a domain reachable worldwide. Furthermore, before the installation, automatically the nearest mirrors are set.

**Comment by Inverstar** [comment]
> Summarizing: on Athena the Internet connection check is done on a domain reachable worldwide. Furthermore, before the installation, automatically the nearest mirrors are set.

Great！Thank you very much！
