### ISSUE TITLE
[BUG] Problems when changing roles

### ISSUE THREAD

**Issue by NoneDev-git** [Athena-OS/athena-iso#43]
Initially I have the role of:
![image](https://user-images.githubusercontent.com/77238864/227741647-8a55e286-a5ef-477a-90e2-2950f9a56e20.png)
1. Select another role     
![image](https://user-images.githubusercontent.com/77238864/227741566-10dfe8ee-e75d-46a5-b7ee-a9cac3bd82df.png)
2. Pressing the "Set your role" button    
3. The installation process    
4. It shows "All done. Your role has been set!"    
![image](https://user-images.githubusercontent.com/77238864/227741602-5df1302d-ca7e-4ddf-9574-c4c7b9d61b96.png)
But in the end, after a re-entry the role in Athena-welcome does not change   
![image](https://user-images.githubusercontent.com/77238864/227741809-77ad466b-07d9-4493-bef9-b2bb4b3ff55a.png)

**Comment by D3vil0p3r** [comment]
Hey @NoneDev-git Thank you for your reporting. I will give a look to it and if I'm able to reproduce the issue, I will fix it. I'll keep you updated.

**Comment by NoneDev-git** [comment]
Okay, thank you.

**Comment by NoneDev-git** [comment]
And when you change, if you answer the question to remove the tools of other roles Y, then the tools of other roles should be unavailable?

**Comment by D3vil0p3r** [comment]
> And when you change, if you answer the question to remove the tools of other roles Y, then the tools of other roles should be unavailable?

They should be uninstalled.

**Comment by NoneDev-git** [comment]
Just may be a problem for me personally because when I change roles and answer Y, I still have tools from another role.

**Comment by D3vil0p3r** [comment]
> Just may be a problem for me personally because when I change roles and answer Y, I still have tools from another role.

So you installed at the beginning Bug Bounty Hunter Role, then you set the role for Enthusiast Student and select y for removing the previous role tools, but you still have Bug Bounty Hunter tools? Btw be aware that some tools of these two roles are the same.

**Comment by NoneDev-git** [comment]
Yes I checked I still have tools that don't match the other role.

**Comment by NoneDev-git** [comment]
> Yes I checked I still have tools that don't match the other role.

Although it is logical because my role in fact, too, does not change.

**Comment by D3vil0p3r** [comment]
@NoneDev-git I fixed it. Run `sudo pacman -Syyu`, reboot the system and use again the stuff about roles, and tell me if it is fixed so we can close this issue.

**Comment by NoneDev-git** [comment]
![image](https://user-images.githubusercontent.com/77238864/227806091-96b3da2f-6860-4773-9510-562464be23e0.png)
I have a problem

**Comment by NoneDev-git** [comment]
![image](https://user-images.githubusercontent.com/77238864/227806218-630292bd-c5c2-4fa8-a336-98df88d942d9.png)
I have a problem

**Comment by D3vil0p3r** [comment]
Try to run "rm -rf $HOME/.config/athena-welcome"

**Comment by NoneDev-git** [comment]
The problem is fixed! Thank you very much.
