### ISSUE TITLE
[BUG]  Error when changing role to black hat.

### ISSUE THREAD

**Issue by NoneDev-git** [Athena-OS/athena-iso#44]
Error when changing role to "Black Hat Omniscient":
![image](https://user-images.githubusercontent.com/77238864/228524212-b9e13066-3375-45e0-b3b5-fdc5aef8a82c.png)
The role is applied but without installing tools for it.

**Comment by D3vil0p3r** [comment]
> Ok thanks:)

Now it should work. Let me know.

**Comment by NoneDev-git** [comment]
Yes, everything works! Thank you.
