### ISSUE TITLE
[ENHANCEMENT] KDE Edition

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Athena-OS/athena-iso#45]
I would like to see a KDE version of it. I always dislike Gnome due to its lack of features and customizability (especially when compared to KDE). The customizations applied to Gnome are great in aesthetics. I really like it. But I have a specific workflow and specific customizations that are not possible in Gnome. Even in Kali Linux, I use KDE and not the default XFCE version. I have previously used Blackarch installed on top of Manjaro. It was fine. But the performance was not that good. I installed Blackarch on top of Athena and it was really going well. If it weren't for Gnome, I wouldn't have uninstalled it. Thanks to you, I came to know more platforms like HTB and THM. I even made accounts in others and solved many challenges. All the time, the performance was so good. I really love the customizations made by you. But Gnome is the biggest obstacle. You may say that KDE is way more bloated and may reduce performance. But Xerolinux is, as they describe it, the best for eye candy lovers and it is extremely good. It is extremely beautiful. I even use it now. So smooth. No lag even with so many customizations. Absolutely beautiful. I can't install Blackarch in this one as it is as a daily driver. That's the problem with this one. This is also the reason I have Kali Linux (separate) as mentioned above. I'd love to see the KDE version. And the best choice for the terminal: Kitty. This choice is excellent. As much as I hate Python for desktop apps (only for desktop apps (GUI terminals included). I love Python for the rest), it is far better than Alacritty. Alacritty is always slower than any other terminal for me. I hate it. Kitty was also customized, and it was fast and smooth.

**Comment by D3vil0p3r** [comment]
Hey! For sure in my mind Athena should give the chance to the user to install the preferred desktop environment, so my intention is to implement also KDE in the future.

**Comment by Inverstar** [comment]
> Hey! For sure in my mind Athena should give the chance to the user to install the preferred desktop environment, so my intention is to implement also KDE in the future.

After I install the xfce desktop version, can I install the gnome desktop again? Can you freely switch between the two desktops?

**Comment by D3vil0p3r** [comment]
> > Hey! For sure in my mind Athena should give the chance to the user to install the preferred desktop environment, so my intention is to implement also KDE in the future.
> 
> After I install the xfce desktop version, can I install the gnome desktop again? Can you freely switch between the two desktops?

In theory yes, but why should you do this?

**Comment by D3vil0p3r** [comment]
KDE version implemented.
