### ISSUE TITLE
Add language 

### ISSUE THREAD

**Issue by MrRezax85** [Athena-OS/athena-iso#48]
First of all, I would like to thank you for creating such a version of Arch Linux.
We Persian users need Athena Persian keyboard support to use Athena OS as a desktop or search the Internet.
 So we ask you to consider this request.🙏

**Comment by D3vil0p3r** [comment]
> First of all, I would like to thank you for creating such a version of Arch Linux. We Persian users need Athena Persian keyboard support to use Athena OS as a desktop or search the Internet. So we ask you to consider this request.🙏

Hey. Athena uses [Calamares](https://github.com/calamares/calamares) as installer for the OS. Could you please open an issue ticket to that GitHub project asking them to implement Persian keyboard support in Calamares?

**Comment by D3vil0p3r** [comment]
Hey @MrRezax85 I give a look to your request and I see that the installer has already Persian keyboard layout:

![image](https://user-images.githubusercontent.com/83867734/233923630-10771eba-4734-4203-934b-852b9e349b31.png)

**Comment by D3vil0p3r** [comment]
So you mean there is a missing keyboard layout. I think the best option is to open an issue here: https://github.com/calamares/calamares/issues/new?assignees=&labels=&template=feature_request.md asking to add in Calamares installer also the specific Persian keyboard layout that fits with your needs.

**Comment by D3vil0p3r** [comment]
@MrRezax85 did you solve the issue with Calamares team?

**Comment by D3vil0p3r** [comment]
We replaced Calamares installer. I close the issue because N/A.
