### ISSUE TITLE
How can i open the terminal?

### ISSUE THREAD

**Issue by Hackerzin23** [Athena-OS/athena-iso#49]
when i try to open the terminal, he's don't open.

**Comment by D3vil0p3r** [comment]
> when i try to open the terminal, he's don't open.

Are you on VM or bare metal? Did you select NVIDIA drivers during installation?

**Comment by Hackerzin23** [comment]
> > when i try to open the terminal, he's don't open.
> 
> Are you on VM or bare metal? Did you select NVIDIA drivers during installation?

i was installed the athena to be my primary OS. yes i did

**Comment by D3vil0p3r** [comment]
If Kitty does not open, it means that your gpu is old.

Btw go to All Applications, open Octopi, go to Terminal tab, run `sudo pacman -S alacritty` and then run `athena-theme-tweak -e alacritty` so u will use Alacritty terminal that should work.

**Comment by Hackerzin23** [comment]
> sudo pacman -S alacritty

i will to try this

**Comment by Hackerzin23** [comment]
> If Kitty does not open, it means that your gpu is old.
> 
> Btw go to All Applications, open Octopi, go to Terminal tab, run `sudo pacman -S alacritty` and then run `athena-theme-tweak -e alacritty` so u will use Alacritty terminal that should work.

i was installed all drivers lmao

**Comment by Hackerzin23** [comment]
> If Kitty does not open, it means that your gpu is old.
> 
> Btw go to All Applications, open Octopi, go to Terminal tab, run `sudo pacman -S alacritty` and then run `athena-theme-tweak -e alacritty` so u will use Alacritty terminal that should work.

right, that's work, thank u!
