### ISSUE TITLE
Failed to install bootloader

### ISSUE THREAD

**Issue by adrhmnhkm** [Athena-OS/athena-iso#51]
![Screenshot from 2023-05-13 22-17-42](https://github.com/Athena-OS/athena-iso/assets/12286739/bc041fc7-d6b0-4206-ba10-e236fd1c5b38)

Is it normal ?

**Comment by adrhmnhkm** [comment]
.. - details: The bootloader could not be installed. The installation command <pre>grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Athena --force</pre> returned error code 1.
2023-05-13 - 22:35:33 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    Calamares will quit when the dialog closes. 
2023-05-13 - 22:35:33 [6]: void Config::doNotify(bool, bool)
    Notification not sent; completion: failed

**Comment by D3vil0p3r** [comment]
At 67% the install time depends on your connection because it downloads package. About the install error I need the generated link and your HW info and if baremetal or vm.

**Comment by adrhmnhkm** [comment]
I try to installing dualboot. Win 11 in SSD and Athena in HDD. I made 4 partitions:

1. /boot/efi
2. /system with btrfs
3. /home with btrfs
4. Swap

**Comment by D3vil0p3r** [comment]
Link generated at error time?

**Comment by adrhmnhkm** [comment]
> Link generated at error time?

https://termbin.com/361e

**Comment by D3vil0p3r** [comment]
At installation time, when you must select the partition to format, on the bottom part you have a drop-down menu for installing the boot loader in a specific location. Could you list here the screenshot and the possible options of that section and drop-down menu option list?

**Comment by adrhmnhkm** [comment]
Fixed. Thanks!
