### ISSUE TITLE
[BUG]: cant open kitt or fish terminal or any program that uses a terminal

### ISSUE THREAD

**Issue by nismo0291** [Athena-OS/athena-iso#54]
### Athena OS version

athena os 2023.02.20

### Are you using baremetal or virtual machine?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine

### Kernel Version

unable to run any command

### Other Software

kitty fish any terminal
any program that uses a terminal
only gui apps working

### Repro Steps

fresh install

### Expected Behavior

io expected a terminal to pop up when clicked on..nuthing happens

### Actual Behavior

nuthing happens

**Comment by D3vil0p3r** [comment]
Come on Discord Athena OS server so you can get the beta release that should solve your issue.

**Comment by nismo0291** [comment]
How do I do that

**Comment by D3vil0p3r** [comment]
By using this link: https://discord.gg/DNjvQkb5Ad

**Comment by D3vil0p3r** [comment]
Solved.
