### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by greedoftheendless** [Athena-OS/athena-iso#55]
## Question
I have a 32 gb usb and used to run kali linux on it. i have erased the usb completly and flashed athena os onto it using balena etcher. i want to run athena os on this usb as a live usb with persistance. can you tell me how to do so?

**Comment by greedoftheendless** [comment]
or is it even possible to do so? and can i get apps such as bluemail and all for it?
and are apps such as disccord. whatsapp and all available?

**Comment by AK1R4S4T0H** [comment]
> or is it even possible to do so? and can i get apps such as bluemail and all for it? and are apps such as disccord. whatsapp and all available?

So I do not know about your persistence issue friend, But Athena does have the ability to use Discord, The ISO currently should already have discord on it. Now i do know that it is based in Arch, So i'm sure anyway to make Arch Persistent would work as a way of making Athena. I personally use Ventoy so i dont know if there is much of a difference from that and Balena Etcher,  but here are some links you might find interesting involving the persistence, https://mags.zone/help/arch-usb.html                                                   https://wiki.archlinux.org/title/Install_Arch_Linux_on_a_removable_medium

**Comment by herycp** [comment]
yeah you can do it.
i do that too but hdd for me not fd .

**Comment by D3vil0p3r** [comment]
@greedoftheendless can we close the issue?

**Comment by greedoftheendless** [comment]
Yeah sure

**Comment by D3vil0p3r** [comment]
Thanks!
