### ISSUE TITLE
[BUG]: No desktop during install, and also after install.

### ISSUE THREAD

**Issue by AdhamNasr** [Athena-OS/athena-iso#56]
### Athena OS version

Athena OS "Polias" v23.06.03

### Are you using baremetal or virtual machine?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine

- [X] ProxMox Virtual Machine

### Repro Steps

- Tested ISO boot and post-install boot in ProxMox with PCI-Passthrough
- Tested ISO boot on MacBook Air 7,2
- Tested ISO boot on MacBook Pro 11,3
- Tested ISO boot on baremetal intel i7 10700

### Expected Behavior

Window manager should load.

### Actual Behavior

All tests resulted in the same error, upon user session load, it halts for sometime, and then boots into a gray screen with an error saying "something went wrong, please log out and log back in again.", you do get the welcome screen and can access the different links, but mouse isn't visible, also calamares works, i tried both login managers thinking it could be the cause, but didn't work, installed i3-wm manually and that worked.

**Comment by D3vil0p3r** [comment]
@AdhamNasr Hey! I am aware of the issue. It was caused by a package related to GDM that created a broken symbolic link instead of a file.

I already fixed and just now I finished to upload the new ISO. Please, download it again from https://sourceforge.net/projects/athena-iso/files/v23.06.03/athena-2023.06.03-x86_64.iso/download

I didn't still test it but it should work. Let me know.

**Comment by AdhamNasr** [comment]
Oh wow, that was quick!! Thanks for the update, I'll download the new one now :)

**Comment by AdhamNasr** [comment]
All good now, installer worked fine on MacBook Air.
Keep up the good work :)

**Comment by D3vil0p3r** [comment]
> All good now, installer worked fine on MacBook Air. Keep up the good work :)

Thank you mate. MacBook Air with which CPU? Intel or ARM?

**Comment by AdhamNasr** [comment]
> > All good now, installer worked fine on MacBook Air. Keep up the good work :)
> 
> Thank you mate. MacBook Air with which CPU? Intel or ARM?

You're welcome :)

It has an intel i5-5250U
