### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by Csprdgst27** [Athena-OS/athena-iso#57]
## Question
how to use this on a virtual machine? :<

**Comment by J-Ciro** [comment]
Just install it as you install any Arch-OS ISO on a Virtual Machine.

**Comment by Csprdgst27** [comment]
done installing it on a virtual box

**Comment by Csprdgst27** [comment]
> Just install it as you install any Arch-OS ISO on a Virtual Machine.

done installing it on older version of virtual box

**Comment by D3vil0p3r** [comment]
@Csprdgst27 I close the issue. If you have still a problem about this, I will reopen it.
