### ISSUE TITLE
[QUESTION]: Terminal

### ISSUE THREAD

**Issue by pantersxx3** [Athena-OS/athena-iso#58]
## Question
How do I change the prompt of the terminals or consoles?

**Comment by D3vil0p3r** [comment]
Which shell are you using?

**Comment by pantersxx3** [comment]
In all of them it has the promp that I want to change, I tried to change PS1 from .bashrc but it did not work, currently I use guake but in fish shell, power shell they also have the customized promp that I would like to change...

**Comment by D3vil0p3r** [comment]
> In all of them it has the promp that I want to change, I tried to change PS1 from .bashrc but it did not work, currently I use guake but in fish shell, power shell they also have the customized promp that I would like to change...

Ok but are you using BASH, FISH or ZSH as shell?

**Comment by pantersxx3** [comment]
echo $SHELL return /usr/bin/zsh, if that's what you mean...

**Comment by D3vil0p3r** [comment]
> echo $SHELL return /usr/bin/zsh, if that's what you mean...

At this point, u should edit `$HOME/.zshrc` file on `PROMPT` variable.

**Comment by pantersxx3** [comment]
Resolved, Thank you very much.
