### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by scavro** [Athena-OS/athena-iso#59]
## Question
First of all, im newbie, and y look for solution but i cant find it.

I tried to update but the system doesnt update:

error: Error de GPGME: No hay datos
:: Sincronizando las bases de datos de los paquetes...
 athena-repository                                                                                   64,5 KiB   411 KiB/s 00:00 [------------------------------------------------------------------------------] 100%
 core                                                                                               131,7 KiB   269 KiB/s 00:00 [------------------------------------------------------------------------------] 100%
 extra                                                                                                8,3 MiB  2,54 MiB/s 00:03 [------------------------------------------------------------------------------] 100%
 community                                                                                           45,0   B   264   B/s 00:00 [------------------------------------------------------------------------------] 100%
 multilib                                                                                           141,6 KiB   319 KiB/s 00:00 [------------------------------------------------------------------------------] 100%
 chaotic-aur                                                                                          2,8 MiB   307 KiB/s 00:09 [------------------------------------------------------------------------------] 100%
 blackarch                                                                                           12,6 KiB  17,4 KiB/s 00:01 [------------------------------------------------------------------------------] 100%
error: Error de GPGME: No hay datos
error: no se han podido sincronizar todas las bases de datos (base de datos no válida o dañada (firma PGP))

I have done the following things and nothing:

$ sudo rm -R /var/lib/pacman/sync
$ sudo pacman -Syu

AND:
sudo rm -rf /etc/pacman.d/gnupg /var/lib/pacman/sync
sudo pacman-key --init 
sudo pacman -Syyu

My pc:
                                                    ┌───────── Hardware Information ─────────┐ 
                                                         ​     H97M-D3H 
                                                         ​     i5-4570 (4) 
                                                         ​ ﬙    GeForce GT 730 
                                                         ​ ﬙    HD Graphics 
                                                         ​ 塞   2810MiB / 7799MiB (36%) 
                                                         ​     1920x1080 
                                                        ├───────── Software Information ─────────┤ 
                                                         ​     6.3.1-zen2-1-zen 
                                                         ​     GNOME 44.1 
                                                         ​     Mutter 
                                                         ​     bash 5.1.16 
                                                         ​     kitty 
                                                         ​     1529 (pacman) 
                                                         ​     i915 
                                                        └──────────────── Colors ─────────────────┘

what can i do to update and upgrade??

Thanks for all

**Comment by shard77** [comment]
Hi, could you try the following?
sudo cp -f "/etc/pacman.conf" "/etc/pacman.conf.orig"
sudo sed -i 's/SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sudo pacman -Syy gnupg archlinux-keyring
sudo mv -f "/etc/pacman.conf.orig" "/etc/pacman.conf"
sudo pacman -Syu

**Comment by scavro** [comment]
Hi, and thank you very much. I have tried with your commands, but the result was:

error: athena-repository: se desconoce el nivel de confianza de la firma de «Antonio Voza <vozaanthony@gmail.com>»
:: Sincronizando las bases de datos de los paquetes...
 athena-repository                                                         64,5 KiB  95,2 KiB/s 00:01 [------------------------------------------------------------] 100%
 core está actualizado
 extra está actualizado
 community está actualizado
 multilib está actualizado
 chaotic-aur está actualizado
 blackarch                                                                  3,9 MiB  1135 KiB/s 00:04 [------------------------------------------------------------] 100%
error: athena-repository: se desconoce el nivel de confianza de la firma de «Antonio Voza <vozaanthony@gmail.com>»
error: no se han podido sincronizar todas las bases de datos (error inesperado)


and  i dont know who Antonio Voza is?? im not 

Thanks for all

**Comment by shard77** [comment]
If you still have an error after that, can you share me the content of `/etc/pacman.conf`?
Thanks

**Comment by scavro** [comment]
Thank you very much shard77, with the lastest commands it works perfectl

Thanks

PD. Do you need me to share the content of pacman.conf ???

**Comment by shard77** [comment]
Nope!
You can close the issue if it's fixed :D 
Have a nice day
