### ISSUE TITLE
pacman -Q | grep pamac  - PACMAN commands not running

### ISSUE THREAD

**Issue by adsulshyam0000** [Athena-OS/athena-iso#6]
pacman -Q | grep pamac  - PACMAN commands not running - How to enable or install in athena os like manjaro os.

pamac support for athena os.

I tried to uninstall code-oss but it not uninstalled.

Any suggestion.

**Comment by D3vil0per** [comment]
@adsulshyam0000  It is strange because I'm testing pamac and I installed it by `paru -S pamac`, and run it as `pamac-manager` by the terminal or by searching on the application menu `pamac`.

About uninstalling code-oss, you can uninstall it by:
```
sudo pacman -R code athena-vscode-themes
```

**Comment by adsulshyam0000** [comment]
Managed to fix.
