### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by barnaclewizard** [Athena-OS/athena-iso#60]
## Question sudo password
Is there a way to get rid of the sudo password requirement? Having to enter the password every five minutes is the only thing keeping me from enjoying this distro.

**Comment by 0xErrors** [comment]
edit visudo file using nano or vim like `sudo EDITOR=nano visudo` and in last line add 
`username ALL=(ALL) NOPASSWD: ALL`  change username to your username and save it 
you can just google small things like this if you got big problem join Athena discord and seek help their 🙂

**Comment by 0xErrors** [comment]
> ## Question sudo password
> Is there a way to get rid of the sudo password requirement? Having to enter the password every five minutes is the only thing keeping me from enjoying this distro.


edit visudo file using nano or vim like sudo EDITOR=nano visudo and in last line add
username ALL=(ALL) NOPASSWD: ALL change username to your username and save it
you can just google small things like this if you got big problem join Athena discord and seek help their 🙂

**Comment by barnaclewizard** [comment]
Awesome thank you! Yeah i couldn't find anything on google  and it was bothering me a lot because it is hands down the sleekest OS I've ever used.
