### ISSUE TITLE
Lightweight Alternative for GNOME[ENHANCEMENT]:

### ISSUE THREAD

**Issue by Ygarr** [Athena-OS/athena-iso#61]
It would be great to suggestion of lightweight GNOME alternative cause on 8Gb pc it`s often happen freeze while build something etc. But not xfce4. May be stylish Icewm or so.

**Comment by D3vil0p3r** [comment]
Im using Athena in a VM with 4 GB and it works well. In the future other Desktop Env (like XFCE) will be implemented.

**Comment by p134c0d3** [comment]
@Ygarr new rolling iso was released last night using the XFCE env for the live environment. If you want to try it out it's at https://sourceforge.net/projects/athena-iso/files/rolling/

**Comment by D3vil0p3r** [comment]
Thank you @p134c0d3 for the reminder. Closing issue as solved.
