### ISSUE TITLE
[QUESTION]:The software package cannot be installed online in China and will get stuck when it reaches 67%

### ISSUE THREAD

**Issue by smz202000** [Athena-OS/athena-iso#63]
## Question
The software package cannot be installed online in China and will get stuck when it reaches 67%

**Comment by D3vil0p3r** [comment]
> ## Question
> The software package cannot be installed online in China and will get stuck when it reaches 67%

It depends on your speed connection. If your connection is slow, proceed with Offline Install, otherwise wait.

**Comment by mpolinowski** [comment]
I was also unable to use the online installer from China. Using the offline option works - updating manually after the installation leads to the usual [mirror](https://unix.stackexchange.com/questions/475236/gpgme-error-on-arch-linux-32bit) and [pacman keys](https://bbs.archlinux.org/viewtopic.php?id=207957) shenanigans. But everything seems to be working now 👍🏻

**Comment by D3vil0p3r** [comment]
> 

Currently there is an outage that will be fixed in 1 hour around. By the way, in 1 hour try to get the beta ISO.
