### ISSUE TITLE
Index athena domain on search engines

### ISSUE THREAD

**Issue by PardesiCat** [Athena-OS/athena-iso#65]
## Proposal
 
hei i think we should list  our the athena domain [athenaos.org](https://www.athenaos.org/) for ranking on search engines 

for that we have to include nice **sitemap**  and **robots.txt**  

ri8 now none of search engine indexing main site   only github link coming

![g](https://github.com/Athena-OS/athena-iso/assets/55957190/58048862-c8f7-41b5-9cb5-a3d941fb4444)
![p](https://github.com/Athena-OS/athena-iso/assets/55957190/78fb2e1d-c2a8-40b8-8448-b86a17482239)

## Example 

like mine 

![robot](https://github.com/Athena-OS/athena-iso/assets/55957190/a471058b-0b19-4431-87b7-3f14d4d87dc1)
![xmll](https://github.com/Athena-OS/athena-iso/assets/55957190/cf33190f-2943-40d5-845f-91e2b6a572f1)

**Comment by D3vil0p3r** [comment]
Implemented
