### ISSUE TITLE
[BUG]: "conda activate" can not work in the ".bashrc" environment.

### ISSUE THREAD

**Issue by Ekkosun** [Athena-OS/athena-iso#66]
### Athena OS version

v23.06.23

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.4.11-zen2-1-zen

### Involved software

miniconda

### Repro steps

For all version of miniconda:

- step 1: `wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh`
- step 2: `bash Miniconda3-latest-Linux-x86_64.sh`
- step 3: `conda init bash`
- step 4: `conda create -n test && conda activate test`

### Expected behavior

the prompt changes from `(base)` to `(test)` 

### Actual behavior

the prompt is still `(base)`

### Diagnostic logs

i find the reason why the prompt doesn't change is that the line in `.bashrc`
`export PROMPT_COMMAND='source ~/.bashrc no-repeat-flag'`
conda adds the conda init lines in ~/.bashrc , but this command execute for every time a command is finished in bash.
so the prompt doesn't change.
``` bash
if [[ $1 != no-repeat-flag  ]]; then
    __conda_setup="$('/home/kumquat/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/home/kumquat/miniconda3/etc/profile.d/conda.sh" ]; then
            . "/home/kumquat/miniconda3/etc/profile.d/conda.sh"
        else
            export PATH="/home/kumquat/miniconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
fi
# <<< conda initialize <<<
conda activate $CONDA_DEFAULT_ENV
```

The code is my solution to this issue

**Comment by D3vil0p3r** [comment]
Thank you very much. Here https://athenaos.org/en/support/troubleshooting/#tools added the details you reported in the issue. I'm not sure to add that code directly on `.bashrc` because Athena has not Conda installed by default.

**Comment by Ekkosun** [comment]
Thank you for your attention。
