### ISSUE TITLE
[QUESTION]: How to change default terminal for applications?

### ISSUE THREAD

**Issue by Sanchit-Newbie** [Athena-OS/athena-iso#68]
I am trying to open applications like:

Auto Wordlists,
Sec Lists,
Payload all the things
mimikatz

It's running but a white terminal comes up. probably xterm. I want to open these applications by default in gnome-terminal. how to do so?

Thanks for this cool and handy OS.

Regards,
Sanchit
[Screenshot from 2023-09-12 21-11-09](https://github.com/Athena-OS/athena-iso/assets/123202995/d6b8ef61-e01f-4c1c-a6e5-66ea007efb14)

**Comment by D3vil0p3r** [comment]
Try `athena-theme-tweak -e gnome-terminal`

**Comment by Sanchit-Newbie** [comment]
Thanks. It worked :)
