### ISSUE TITLE
[QUESTION]: How to configure keyboard shortcuts?

### ISSUE THREAD

**Issue by Sanchit-Newbie** [Athena-OS/athena-iso#69]
I choose my role as Red Teamer and installed everything.
No menu based shortcuts are working for me but rest other.
When I try to run shortcuts like CTRL+SPACE , Ctrl + Shift + A those shortcuts don't work. 
However shortcuts such as Win+Tab works. Ctrl + C works

How to configure them?

Regards,
Sanchit

**Comment by D3vil0p3r** [comment]
Hey. Those two shortcuts are related to a GNOME extension. Currently there is a migration to GNOME 45 that will be effective at the end of September. Several GNOME extensions packages have been already updated to work on GNOME 45 but of course they dont work on GNOME 44 (that is currently on Athena), so you need to wait the end of September or uninstall those extensions packages and installing manually older version of those extensions.

**Comment by Sanchit-Newbie** [comment]
Ok, So will i need to update it myself at the end of month or it would happen automatically?

**Comment by p134c0d3** [comment]
@Sanchit-Newbie you can go to [extensions.gnome.org](https://extensions.gnome.org/) and if you click on the "Installed Extensions" tab, it should show an icon if there is an update available for that extension that looks like: 
![image](https://github.com/Athena-OS/athena-iso/assets/70922864/4a9e84da-9deb-4313-af7d-ac26bead68f5)

I would recommend turning off the extension before upgrading it. Unfortunately I don't know of a way for Gnome extensions to automatically update themselves. I just installed the new release at https://sourceforge.net/projects/athena-iso/files/rolling/ and checked if those are working and all three menus are working (red team, blue team, and PWNage menus). You may download the latest rolling-release iso and give it a try again.

**Comment by p134c0d3** [comment]
@Sanchit-Newbie if you want to configure the keyboard shortcuts you can go into Extensions and Settings for the FlyPie extension, and set the shortcuts for the menus to whatever you'd like. Hope this helps!
