### ISSUE TITLE
[BUG]: sddm-theme-astronaut not found

### ISSUE THREAD

**Issue by Kptainflintt** [Athena-OS/athena-iso#70]
### Athena OS version

2023.06.23

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.3.9-zen1-zen

### Repro steps

Update Calamares
Update mirrors.
Launch online install on bare-metal laptop.
Choose SDDM for login page.

Install failed before the end, error is "The command <i>pacman -S --needed --noconfirm sddm-theme-astronaut</i> ended with exit code 1."

If the command is run in shell : target not found : sddm-theme-astronaut

### Expected behavior

Installation skip login manager in order to have a working OS, we can install it after.

### Actual behavior

Installer crash

### Diagnostic logs

http://termbin.com/wuvl

**Comment by D3vil0p3r** [comment]
The missing package on Chaotic AUR has been rebuilt. Try now please.
