### ISSUE TITLE
[QUESTION]:How to only use the dedicated GPU besides a freezing problem in the UI.

### ISSUE THREAD

**Issue by oXno0neXo** [Athena-OS/athena-iso#71]
## Question
Hello,
My laptop has dedicated&integrated GPU so i wanted to ask if there's a way to just use just the dedicated one because i faced some freezing in the UI and a black screen or absence of the login manager after powering up the the device from suspending multiple times and i don't know if it's a conflict between using both of them i really don't know.
Here's the output of nvidia-bug-report.sh:
[nvidia-bug-report.log.gz](https://github.com/Athena-OS/athena-iso/files/12642025/nvidia-bug-report.log.gz)
I hope if there's anything to do with the freezing issue and please tell me if you need any information.
Regards.

**Comment by D3vil0p3r** [comment]
You can switch to dedicated GPU by `envycontrol` command. For freezing issue downgrade your kernel and kernel headers packages to a previous version.

**Comment by oXno0neXo** [comment]
> You can switch to dedicated GPU by `envycontrol` command. For freezing issue downgrade your kernel and kernel headers packages to a previous version.

If you don't mind can you tell me how to downgrade the kernal and the kernal packages or mention any resource that i can follow?

**Comment by D3vil0p3r** [comment]
Which kernel u have?

**Comment by oXno0neXo** [comment]
> Which kernel u have?

6.4.12-zen1-1-zen

**Comment by D3vil0p3r** [comment]
`sudo downgrade linux-zen linux-zen-headers` then u need to select a previous version, for example 6.5.1 or 6.4.x and reboot

**Comment by oXno0neXo** [comment]
> `sudo downgrade linux-zen linux-zen-headers` then u need to select a previous version, for example 6.5.1 or 6.4.x and reboot. Are you in baremetal or vm?

Sorry for being late in replying. I am in baremetal.

**Comment by D3vil0p3r** [comment]
If you run `top` for 10 15 seconds can you tell me what is the process that is taking more cpu and how much percentage?

**Comment by oXno0neXo** [comment]
> If you run `top` for 10 15 seconds can you tell me what is the process that is taking more cpu and how much percentage?

The gnome-shell process is the most process appeared at the top of the list with 2->3 percentage of the cpu.

**Comment by D3vil0p3r** [comment]
It is strange you get freezing and you dont have high CPU usage. What about RAM? Is there some processing taking a lot of RAM? How much RAM u have?

**Comment by oXno0neXo** [comment]
> It is strange you get freezing and you dont have high CPU usage. What about RAM? Is there some processing taking a lot of RAM? How much RAM u have?

I have 16 GB. I face the freezing issue most of times when i launch an emulator like Genymotion/Android Studio emulator to some android application testing in addition to using tools like jadx-gui/jadx to get the source code of the APK, Although when i use them combined the cpu get to 30->40 percentage and memory 40->50 percentage sometimes everything go well but the other times the device throws the freezing issue.

**Comment by D3vil0p3r** [comment]
That spike is caused by those tools?

**Comment by oXno0neXo** [comment]
> That spike is caused by those tools?

Yeah, most of the times.

**Comment by oXno0neXo** [comment]
But i understand the for decompiling or using an emulator or virtual machine the usage percentage of the ram&cpu should be kind of high but it's not above 80/90 percent so i don't know what's the source of this freezing issue.

**Comment by D3vil0p3r** [comment]
Maybe it could be discussed with the devs of these tools why they take so many resources

**Comment by oXno0neXo** [comment]
I'll search in their github page for any question related to this issue, Anyway, Thanks for helping me to this point.

**Comment by D3vil0p3r** [comment]
> > `sudo downgrade linux-zen linux-zen-headers` then u need to select a previous version, for example 6.5.1 or 6.4.x and reboot. Are you in baremetal or vm?
> 
> Sorry for bothering you again but after i tried to use just the dedicated GPU i faced the freezing issue again so i tried to downgrade the kernal version as you mentioned and i did choose 6.5.1 but now whenever i open my device i just face a black screen without even the login manager appearing at all. Is there anything i can do?

You don't bother me, I appreciate your feedback. 6.5.1 is still bugged. You must choose a kernel version that is less than 6.5.x, so you can downgrade to 6.4.12 for example, or choosing linux-lts as kernel that is more stable than the existing ones.

**Comment by oXno0neXo** [comment]
> > > `sudo downgrade linux-zen linux-zen-headers` then u need to select a previous version, for example 6.5.1 or 6.4.x and reboot. Are you in baremetal or vm?
> > 
> > 
> > Sorry for bothering you again but after i tried to use just the dedicated GPU i faced the freezing issue again so i tried to downgrade the kernal version as you mentioned and i did choose 6.5.1 but now whenever i open my device i just face a black screen without even the login manager appearing at all. Is there anything i can do?
> 
> You don't bother me, I appreciate your feedback. 6.5.1 is still bugged. You must choose a kernel version that is less than 6.5.x, so you can downgrade to 6.4.12 for example, or choosing linux-lts as kernel that is more stable than the existing ones.

Thanks for replying again. I downgraded the kernal again to 6.4.12 by openning different TTY but when i reboot the device the login manager stil doesn't appear.

**Comment by D3vil0p3r** [comment]
Come on Discord, you can screenshare to me so I can check directly

**Comment by oXno0neXo** [comment]
> Come on Discord, you can screenshare to me so I can check directly

Ok i joind the channel.
