### ISSUE TITLE
[QUESTION]: Online install failed due to package manage error?

### ISSUE THREAD

**Issue by RayneScofield** [Athena-OS/athena-iso#73]
## Question
Hi I'm using the latest rolling iso (2023-09-22) https://sourceforge.net/projects/athena-iso/files/rolling/
I've verified the sha256, it is matched.

install into vmware workstation using online install option,
but get this package manage error:
![image](https://github.com/Athena-OS/athena-iso/assets/45684550/96947af6-bf56-4ac0-866b-504fd833b90a)

Does someone in the same situation with me?
looks like the online installation is broken, should go with the offline installation?

thanks in advance

**Comment by D3vil0p3r** [comment]
Hey. The error occurred because the ISO maintained tor-browser package that some days ago its maintainer renamed as tor-browser-bin. So I should create and upload a new ISO.

Currently, to use the ISO, install it by Offline Installer and when you land on the environment, remove tor-browser package by `sudo pacman -R tor-browser` and install tor-browser-bin package.

**Comment by RayneScofield** [comment]
thanks very much

**Comment by HXN2** [comment]
I am facing the same problem. Can someone help me with all the commands, please?

**Comment by D3vil0p3r** [comment]
> I am facing the same problem. Can someone help me with all the commands, please?

I'm uploading a new ISO just now. It will have a new installer backend but with a temporary GUI. It will be uploaded when this workflow is completed: https://github.com/Athena-OS/athena-iso/actions It needs around 1h.

**Comment by HXN2** [comment]
How do I download it?

**Comment by D3vil0p3r** [comment]
> How do I download it?

Now it is in SourceForge in rolling release. It has a beta new installer. During the installation you could see some "ERROR" strings. They are not errors, they are just warning that pacman sees as errors. U need only to reach the end of the installation. note that currently LiightDM is bugged due to webkit2gtk update that broke it, and if u use VMware, use Linux LTS kernel. Remember that Hyprland is not supported for VMs.

**Comment by HXN2** [comment]
Give me a link if you can, thank you

**Comment by HXN2** [comment]
> > How do I download it?
> 
> Now it is in SourceForge in rolling release. It has a beta new installer. During the installation you could see some "ERROR" strings. They are not errors, they are just warning that pacman sees as errors. U need only to reach the end of the installation. note that currently LiightDM is bugged due to webkit2gtk update that broke it, and if u use VMware, use Linux LTS kernel. Remember that Hyprland is not supported for VMs.




Oh, I downloaded it. The site says it was updated 8 hours ago. Thank you, our developer

**Comment by HXN2** [comment]
Also I use VMware What do I do options in the installation

**Comment by D3vil0p3r** [comment]
https://athenaos.org/en/installation/install-guest-vmware/

**Comment by HXN2** [comment]
I want it to be an installed version forever. I do not want a live version. Is it possible and how?

**Comment by D3vil0p3r** [comment]
> I want it to be an installed version forever. I do not want a live version. Is it possible and how?

The ISO you download has Install option to get a "forever" version.

**Comment by HXN2** [comment]
I want the installed version forever. I do not want the live version. Is it possible and how? I can choose any kernel version

**Comment by D3vil0p3r** [comment]
> I want the installed version forever. I do not want the live version. Is it possible and how? I can choose any kernel version

As I said above.

**Comment by HXN2** [comment]
Please return the appearance of the themes that appear when choosing a theme, like the previous update + How do I know the saved version instead of Live User?

**Comment by D3vil0p3r** [comment]
> Please return the appearance of the themes that appear when choosing a theme, like the previous update + How do I know the saved version instead of Live User?

as I wrote above, it is a temporary installer. When we finish to develop the new installer GUI, also theme appearance will be provided.

**Comment by HXN2** [comment]
I am watching a video and it installs normally, then when I log in again it chooses to restore a previous system and it comes in a preserved form.

**Comment by D3vil0p3r** [comment]
Join Discord because your point is not clear

**Comment by HXN2** [comment]
watch it!! 


https://www.youtube.com/watch?v=5-unLy4y_S4&t=651s
https://www.youtube.com/watch?v=5-unLy4y_S4&t=651s
https://www.youtube.com/watch?v=5-unLy4y_S4&t=651s

**Comment by D3vil0p3r** [comment]
@HXN2 this behavior is not accepted. Issue is closed.
