### ISSUE TITLE
[QUESTION]: Please help... so lost

### ISSUE THREAD

**Issue by jasidok** [Athena-OS/athena-iso#76]
## Question
At first when I was trying to install from the installer I kept getting an error message. the message was similar to : command athena theme not found </> error 1. and after so much digging i finally figured out that i think it had to do with Grub2 and the live install changing locations for the files. But I found the few paragraphs that had the answer, and I literally couldn't figure out what they were saying. Finally, I found a video that helped me to mount the partition that i had made in Gparted. I made it corrrectly, I promise you that. It was a full bare metal installl on the disk, I have multiple disks on this pc. I have three partitions, 8mb, 300mb, and then the rest. the grub, boot, and root. I did it to a T following the instructions. I ended up making the big partition ext4 just in case that was what was wrong. Every single time i tried to do the install, it gave me the same answer. And this is hours of trying.... Finally after i mounted the partitions, the install (still gave me the same error) but I knew it was successful. So I restarted. And bam. here it is. But..... There are a bunch of files misssing and i can't figure out what is wrong. I have added the repositiories to the best of my ability. I don't understand. Whne I push ctrl+space bar, nothing happens. When I run htb-update, it says to put in the app token after the password, and i have no idea where the app token is. When i click htb update on the wlecome screen it says... Check if your API key is incorrect or expired. Renew your API key by running 'htb-toolkit -k reset'. Error details: expected value at line 1 column 1
Press Enter to continue...

**Comment by D3vil0p3r** [comment]
Hey. On Athena website, Discord and other platforms, the reason of not showing menu or setting htb api are described there. For the menu we must wait gnome 45. I wrote this so many times. Please I invite you to read the bulletin in the website or join our Discord

**Comment by jasidok** [comment]
Oh man. How did I miss a detail like that. That's my bad. Thank you for letting me know. Ok so it still feels like there's something missing. Although it does run ok. But when I open the "Software" app there are only a couple boxes that loads and when I click over to update, it says that error message. I'm not home right now so I can't give you exacts, I apologize. But I'll have to take another look at everything after reading what you're talking about. I'm in the discord so I'll start reading and post again later.

**Comment by umop3plsdn** [comment]
it seems 45 is out on the main arch repos. Although it didn't fix the issue when upgraded. Do you know how to manually fix it now that it's released?

**Comment by D3vil0p3r** [comment]
Which error you get?

**Comment by p134c0d3** [comment]
@umop3plsdn go ahead and download the latest rolling release iso from SourceForge. @D3vil0p3r just put a new one out a day or two ago and install has worked fine for me (I always update the mirrorlist before starting the online install). I was having the same issue and this new iso has fixed that for me. You'll fine it at https://sourceforge.net/projects/athena-iso/files/rolling/

Hope this helps.
