### ISSUE TITLE
[BUG]: Installing Hyprland installs GNOME and breaks networking

### ISSUE THREAD

**Issue by 3top1a** [Athena-OS/athena-iso#77]
### Athena OS version

Athena OS (idk I downloaded rolling from sourceforge today on 10/10/2023)

### Which environment or technology are you using?

- Baremetal
- VMware Virtual Machine

### Kernel version

6.5.6-arch2-1

### Involved software

- Selected hyprland in install

### Repro steps

- Download fresh installation ISO from sourceforge
- Boot into installer
- Install, left default otherwise
    - Czech language (default)
    - Shell: Fish
    - Terminal: foot
    - WM: hyprland
- reboot

### Expected behavior

- Installed hyprland
- Network doesn't work

### Actual behavior

[aegis.log](https://github.com/Athena-OS/athena-iso/files/12860678/aegis.log)
[packages.log](https://github.com/Athena-OS/athena-iso/files/12860679/packages.log)
![2023-10-10T20:28:09,731323788+02:00](https://github.com/Athena-OS/athena-iso/assets/57371001/6975ff94-ddb0-41c2-bb23-29fa26f994a3)

**Comment by D3vil0p3r** [comment]
```
[ INFO ] 20:17:15 Installing desktop : "hyprland"
[ INFO ] 20:17:15 No desktop setup selected!
```
There is a bug on the installer when the user select Hyprland I see... I should fix it

**Comment by umop3plsdn** [comment]
ya it seems to not only install gnome(x and wayland) but plasma as well. Although I didn't have that issue with networking OP has

**Comment by D3vil0p3r** [comment]
U see gnome install because you choose GDM (GNOME Display Manager) as Display Manager but it is not an issue. Plasma bcs of some dependency. By the way try now to redownload the rolling release and select Hyprland. After the install, at login time, remember to select Hyprland as session. Ps: u can use GDM but I suggest to use SDDM if you dont want to see gnome sessions. Up to you

**Comment by 3top1a** [comment]
It seems it has installed but hyprland doesn't like vmware's software GPU, so I'll test it more tomorrow.
Here are the logs:

[aegis.log](https://github.com/Athena-OS/athena-iso/files/12885081/aegis.log)
[pacman.log](https://github.com/Athena-OS/athena-iso/files/12885082/pacman.log)

**Comment by D3vil0p3r** [comment]
> It seems it has installed but hyprland doesn't like vmware's software GPU, so I'll test it more tomorrow. Here are the logs:
> 
> [aegis.log](https://github.com/Athena-OS/athena-iso/files/12885081/aegis.log) [pacman.log](https://github.com/Athena-OS/athena-iso/files/12885082/pacman.log)

Hyprland is not supported in virtualization environment like VMware Workstation or Virtualbox.
