### ISSUE TITLE
Some tools won’t open

### ISSUE THREAD

**Issue by Kushy420** [Athena-OS/athena-iso#8]
I tried installing default one and hardened kernel image and both times these apps refuse to open powersploit,payloadsallthethings,Fuzzdb,SeclistsMimikatz,securitywordlists and a few others . Is there something that I can do to fix this

**Comment by D3vil0per** [comment]
> I tried installing default one and hardened kernel image and both times these apps refuse to open powersploit,payloadsallthethings,Fuzzdb,SeclistsMimikatz,securitywordlists and a few others . Is there something that I can do to fix this

Hey @Kushy420 Remember that on Athena, for optimizing disk space, when you access the first time to a resource, it asks you for installing/downloading the resource itself. Are you connected to Internet?
If you wish, reach me on Discord (link on main GitHub page) so we can give a look together.

**Comment by mkdirlove** [comment]
Theme is not installing.
How do i install it?


tnx :)
