### ISSUE TITLE
[QUESTION]:How do I uninstall the additional apps that came with Athena

### ISSUE THREAD

**Issue by Threeoaks** [Athena-OS/athena-iso#82]
## Question
In my menu there are a lot of apps that came with Athena . Uninstall of th  program did not remove them

**Comment by p134c0d3** [comment]
Are you saying that "sudo pacman -Rns <package name>" didn't work?

**Comment by D3vil0p3r** [comment]
If you mean hacking tools, at the beginning you can see them in your menu but they are not installed in your system, unless you click on them and start their installation

**Comment by Threeoaks** [comment]
In my menu Athens got listed twice. One icon had a lot of apps for Athena.
Nothing is moving them. Can't uninstall

**Comment by D3vil0p3r** [comment]
Screenshot or evidence please

**Comment by Threeoaks** [comment]
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by D3vil0p3r** [comment]
@Threeoaks come on our Discord. Here it is not clear what you need.

**Comment by Threeoaks** [comment]
I don’t see am Athena group on Discord. How do I find it?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by D3vil0p3r** [comment]
@Threeoaks https://discord.gg/AHXqyJHhGc

**Comment by Threeoaks** [comment]
Says link expired right off

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by D3vil0p3r** [comment]
Try this link https://discord.com/servers/athena-os-977645785170714644 and click on **Join Server**
