### ISSUE TITLE
[BUG]: alternative keyboard mappings are not recognised by GDM login

### ISSUE THREAD

**Issue by munkinut** [Athena-OS/athena-iso#85]
### Athena OS version

Athena OS Polias

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.5.10-hardened1-1-hardened

### Involved software

GDM

### Repro steps

Change keyboard settings in Installer, set user password to "#####", complete the installation, reboot, go to login with GDM, password does not work because # and £ are not mapped correctly at this stage.

### Expected behavior

Expected kb mappings for en-gb keyboard to be recognised by GDM.

### Actual behavior

Expected kb mappings are not recognised by GDM and password entry fails unless you type "£££££" on the GB keyboard.

**Comment by D3vil0p3r** [comment]
Fixed: https://github.com/Athena-OS/aegis/commit/8b6cebae596b7bf31268eab21ae6c3d08177f134

Thank you!
