### ISSUE TITLE
[BUG]: Updates causing unwanted changes to GRUB config on dual-boot system

### ISSUE THREAD

**Issue by munkinut** [Athena-OS/athena-iso#86]
### Athena OS version

Athena OS Polias

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.5.10-hardened1-1-hardened

### Involved software

GRUB

### Repro steps

Create a dual-boot with Debian as the other Linux OS (use Debian expert installer to skip GRUB installation).
Use Grub Customizer to add in the Debian OS to GRUB.
Save the config and write to MBR.
Test that both OS's appear when rebooting, and can be started through GRUB.
Boot into Athena OS, perform an update of Athena OS.
The updater overwrites the GRUB config, leaving only the Entries for Athena OS (the Debian ones are missing).

### Expected behavior

Athena OS updater should edit the GRUB config in such a way as to preserve the entries added by GRUB Customizer during the process of setting up the dual-boot configuration.

### Actual behavior

Entries in GRUB config are not preserved during an update of Athena OS.
Rebooting after an update shows that (where new entries had been added) entries are now missing.

**Comment by D3vil0p3r** [comment]
Fixed mkinitcpio hooks and changed the logic to trigger the GRUB update. A `sudo pacman -Syyu` should be enough.
