### ISSUE TITLE
[QUESTION]: Hyprland configs error installation

### ISSUE THREAD

**Issue by sherloCod3** [Athena-OS/athena-iso#87]
Hello, first of all, I would like to thank you for the work on the beautiful distro. I would like to ask for help with a problem during the installation of the **Hyprland** version. 
When I tried to install for the first time, I received an error with the package "**python-material-color-utilities**". The error was "**Maximum file size exceeded error: failed retrieving file...**" while downloading and installing "**athena-hyprland-config-439.c10884e8-1**". This "python-material" package was initially trying to download from "**chaotic-aur**" using the default settings. Even trying to clear the cache and pacman packages, reinstall the keys for chaotic, update the mirrorlist, and try again, the error persisted. This happened during the installer process and also after the partial installation that was completed due to the error. I opened a TTY and downloaded the problematic package from AUR, and the installation finished, but your version's configurations were not installed, only the programs. 
I am currently using the basic example version, without polybar, waybar, the raw version of Hyprland. Regarding the error with the mentioned package, I tried several solutions found on Google, but without success. Even after installing the necessary packages, the configurations did not install properly. If you could help me, please. Thank you in advance!

**Comment by D3vil0p3r** [comment]
Hyprland is still in development.

**Comment by sherloCod3** [comment]
Ok, got it, thank you!
