### ISSUE TITLE
[BUG]: I can't install in VMware

### ISSUE THREAD

**Issue by Elvis-me** [Athena-OS/athena-iso#89]
### Athena OS version

rolling

### Which environment or technology are you using?

- [ ] Baremetal
- [ ] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

I encountered issues during the installation on VMware and couldn't complete the installation.

### Expected behavior

![屏幕截图 2023-11-23 213532](https://github.com/Athena-OS/athena-iso/assets/61863247/9648de54-9284-4b31-826b-a749a9aefe93)

### Actual behavior

[Out.txt](https://github.com/Athena-OS/athena-iso/files/13450507/Out.txt)

**Comment by D3vil0p3r** [comment]
```
:: Synchronizing package databases...
error: failed to synchronize all databases (no servers configured for repository)
```
It seems that when the installer tried to contact mirrors, there were no mirrors that responded to you.
Are you connecting to Internet? Do you have some firewall or connection security mechanisms that could block some connections to the repositories?

**Comment by Elvis-me** [comment]
I'm in China and might not be able to connect to the mirror server. Is there a way for me to install offline?Thank you，

**Comment by D3vil0p3r** [comment]
> I'm in China and might not be able to connect to the mirror server. Is there a way for me to install offline?Thank you，

I guess your issue is related to the Great Firewall in China. You should use a VPN to install it, currently there is no a Offline installer.

**Comment by Elvis-me** [comment]
I appreciate your patient response. I will try using a VPN.
