### ISSUE TITLE
[BUG]: SHA256 Sum does not match

### ISSUE THREAD

**Issue by ClayplugLLC** [Athena-OS/athena-iso#90]
### Athena OS version

new release, Polias

### Which environment or technology are you using?

- [ ] Baremetal
- [X] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

On Windows, typed

`certutil -hashfile athena-rolling-x86_64.iso sha256`

### Expected behavior

The hash value: a1498cd9d8c0bdafeab21f83c2481cc3719255fba1093963fd03664005a66689

### Actual behavior

Got the hash value of aabfdcc5771b7a0dc61a709360a25ebcc2fdf9644bce2b6477ed4379b45be5af

**Comment by D3vil0p3r** [comment]
What s the source you downloaded the ISO?

**Comment by bambam2984** [comment]
I am noticing the same problem. I have downloaded from all sources and the hash returned is:

 AABFDCC5771B7A0DC61A709360A25EBCC2FDF9644BCE2B6477ED4379B45BE5AF

**Comment by D3vil0p3r** [comment]
Sorry guys. The hash `a1498cd9d8c0bdafeab21f83c2481cc3719255fba1093963fd03664005a66689` was an old one. Currently the Athena ISO is deployed automatically weekly so each week the ISO file and related hashes change. I fixed the text of the release description. You can use the hash files at the bottom if release page. Thank you for your reporting.
