### ISSUE TITLE
[BUG]: Installation(Online) error

### ISSUE THREAD

**Issue by deepinsideDrury** [Athena-OS/athena-iso#93]
### Athena OS version

Athena OS live

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

Installation(Online)
[Select Keyboard Layout]
Region China
[Select Timezone]
Region Asia
Zone Shanghai

### Expected behavior

install success

### Actual behavior

error

### Diagnostic logs

[install.log](https://github.com/Athena-OS/athena-iso/files/13467054/install.log)

**Comment by D3vil0p3r** [comment]
Error related to Chaotic mirror on `edex-ui-bin` package. I opened an issue to Chaotic AUR team.
