### ISSUE TITLE
Athena is installar not show 

### ISSUE THREAD

**Issue by Sumangal44** [Athena-OS/athena-iso#99]
![17040919215275396709506266151875.jpg](https://github.com/Athena-OS/athena-iso/assets/123644743/4015fe4c-04fc-4aa3-af75-d576645edc1d)

Not show this installar  please solve this

**Comment by D3vil0p3r** [comment]
You are using an old ISO

**Comment by Sumangal44** [comment]
2023.6.23 version

**Comment by D3vil0p3r** [comment]
Download the rolling ISO

**Comment by Sumangal44** [comment]
Thanks, I will!

**Comment by Sumangal44** [comment]
what i download  please make guide

**Comment by D3vil0p3r** [comment]
https://github.com/Athena-OS/athena-iso/releases/download/v23.06.23/athena-rolling-x86_64.iso

**Comment by Sumangal44** [comment]
> https://github.com/Athena-OS/athena-iso/releases/download/v23.06.23/athena-rolling-x86_64.iso

this is same new install process you send me which version i download athena os installer   please i cant install

**Comment by Sumangal44** [comment]
> ![17040919215275396709506266151875.jpg](https://private-user-images.githubusercontent.com/123644743/293572361-4015fe4c-04fc-4aa3-af75-d576645edc1d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDA3ODEsIm5iZiI6MTcwNDE0MDQ4MSwicGF0aCI6Ii8xMjM2NDQ3NDMvMjkzNTcyMzYxLTQwMTVmZTRjLTA0ZmMtNGFhMy1hZjc1LWQ1NzY2NDVlZGMxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQyMDIxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDUyMTlkYjlhYWIwZjg5ZjJkZGZjNmU4N2FmNzM1OWVjNzE4YWJlNWQxY2U4Njg1Yjc0NWRhZmFmYzBjZTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YgA5eV6MT_HL1Gz3Vg3ch3jKf8WA-lWrYUIYxC-XV_0)
> 
>this process i do please which version i download

**Comment by Sumangal44** [comment]
Iso download iso file it's working

**Comment by D3vil0p3r** [comment]
Ok. I close the issue.
